### PR TITLE
ci: add travis.yml

### PR DESCRIPTION
**Pull request by borgified**

### CODE REVIEW

**Comment by borgified** [comment]
for this to work, still need to enable the travis app on this repo. (i dont have owner permissions to this repo, so you have to follow these steps for me: https://docs.travis-ci.com/user/tutorial/)

**Comment by Alan-R** [comment]
I enabled travis access.

**Comment by Alan-R** [comment]
I would rather you use tox. Tox sets up separate virtual environments. Is there some reason why you're not using it?

**Comment by borgified** [comment]
yea im gonna use tox, im testing it on my fork but ill move the stuff over to here now that i have access.
i actually didnt realize i was supposed to use tox earlier, i just used whatever travis was telling me the default was. hang on.. ill fix

**Pull request merged**
